---
title: 'Implementing semPLS'
author: "Lộc"
date: "2023-03-07"
output: html_document
---
# Nhập dữ liệu
```{r}
library("semPLS")
data("mobi")
data("ECSImm")
data("ECSIsm")
```

# Tạo biến PLS sem:
```{r,warning=T}
#Creating an object suited for use with the fitting function sempls:
ECSI <- plsm(data = mobi, strucmod = ECSIsm, measuremod = ECSImm)
names(ECSI)
```
```{r}
mvpairs(model = ECSI, data = mobi, LVs = "Expectation")

ecsi <- sempls(model = ECSI, data = mobi, wscheme = "centroid")
```

```{r}
#Display graphic
pathDiagram(ecsi, 
            file = "ecsiStructure", 
            full = FALSE, #only the structural model is processed.
            edge.labels = "both", #names of the parameters and values are both printed
            output.type = "graphics", #
            digits = 2,
            graphics.fmt = "pdf")
ecsi
```

# Mô tả các criteria indexs của model:
```{r}
names(ecsi)
```

```{r}
#Xuất R^2 của model
rSquared(ecsi)

#Xuất giá trị Dillon-Goldstein's rho
dgrho(ecsi)
```

```{r}
#Xuất Path coeffection 
pC <- pathCoeff(ecsi)
print(pC, abbreviate = TRUE, minlength = 3)
```

```{r}
#Xuất total effect:
tE <- totalEffects(ecsi)
print(tE, abbreviate = TRUE, minlength = 3)
```


```{r}
#Xuất kết quả outer weights:
plsWeights(ecsi)
```

```{r}
#Xuất kết quả loadings của model:
lE<-plsLoadings(ecsi)
print(lE,abbreviate = TRUE, minlength = 3,reldiff=0.2)

```
```{r}
plsLoadings(ecsi)
```
-->Chỉ số loadings có thể dùng để check discriminant validity.(Cho plsLoadings() vào object và print thêm argument reldiff=0.2)

```{r}
ecsi$cross_loadings
```
# Booptrap to estimate
```{r}
#Using booptrap method to estimate outer loadings and path coefficients
set.seed(123)
ecsiBoot <- bootsempls(ecsi, nboot = 500, start = "ones", verbose = FALSE)
ecsiBoot
```


```{r}
#Plotting 
densityplot(ecsi, use = "residuals")
```


```{r}
#Calculating confidence intervals based on the percentile method
ecsiBootsummary <- summary(ecsiBoot, type = "bca", level = 0.9)
ecsiBootsummary
```


```{r}
#Plotting kernel density estimates:
densityplot(ecsiBoot, pattern = "beta")

#Plotting parallel coordinates:
parallelplot(ecsiBoot, 
             pattern = "beta", 
             reflinesAt = c(0, 0.5),
             alpha = 0.3, 
             type = "bca",
             main = "Path Coefficients\nof 500 bootstrap samples")

```